version: 2
# CircleCI integration with Drupal 8.

# Reusable steps.

## Add SSH Key
add_ssh: &add_ssh
  add_ssh_keys:
    fingerprints:
      - "6f:84:bf:38:2c:c5:fe:25:46:14:94:54:f3:22:42:f5"

## Add Known Hosts
add_known_hosts: &add_known_hosts
  run:
    name: Add SSH Known Hosts
    command: |
      ssh-keyscan svn-23450.prod.hosting.acquia.com >> ~/.ssh/known_hosts
      ssh-keyscan stanfordgryphondev.ssh.prod.acquia-sites.com >> ~/.ssh/known_hosts
      ssh-keyscan stanfordgryphonstg.ssh.prod.acquia-sites.com >> ~/.ssh/known_hosts
      ssh-keyscan stanfordgryphon.ssh.prod.acquia-sites.com >> ~/.ssh/known_hosts
      ssh-keyscan -t rsa,dsa github.com >> ~/.ssh/known_hosts

## Defines the cache restoring mechanism.
restore_caches: &restore_caches
  restore_cache:
    # We use the composer.lock as a way to determine if we can cache our build.
    keys:
      - cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "composer.lock" }}
      # fallback to using the latest cache if no exact match is found
      - cache-{{ .Environment.CACHE_VERSION }}-

## Defines the cache saving mechanism.
save_caches: &save_caches
  save_cache:
    paths:
      - ./vendor
      - ./docroot/modules/contrib
      - ./docroot/modules/custom
      - ./docroot/profiles/contrib
      - ./docroot/profiles/custom
      - ./docroot/themes/contrib
      - ./docroot/themes/custom
      - ./docroot/libraries
      - ./docroot/core
    key: cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "composer.lock" }}

## Defines images and working directory.
defaults: &defaults
  docker:
    - image: pookmish/drupal8ci:latest
    - image: selenium/standalone-chrome:latest
    - image: circleci/mysql:5.7
      environment:
        MYSQL_DATABASE: drupal
        MYSQL_USER: drupal
        MYSQL_PASSWORD: drupal
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
  working_directory: /var/www/html

sdssgryphon_codeception_acceptance: &sdssgryphon_codeception_acceptance
  <<: *defaults
  steps:
    - checkout
    - *restore_caches
    - run:
        name: Run Codeception Acceptance Tests
        command: |
          composer install --no-interaction
          vendor/bin/blt blt:telemetry:disable --no-interaction
          mkdir -p artifacts/_data
          vendor/bin/blt circleci:drupal:install --profile=sdss_profile --no-interaction
          vendor/bin/blt drupal:toggle:modules --no-interaction
          vendor/bin/drush xmlsitemap-regenerate
          vendor/bin/blt tests:codeception --test=sdss --no-interaction
    - *save_caches
    - store_test_results:
        path: artifacts
    - store_artifacts:
        path: artifacts

phpunit_coverage: &phpunit_coverage
  <<: *defaults
  steps:
    - checkout
    - *restore_caches
    - run:
        name: Run PHPUnit Coverage Tests
        command: |
          composer install --no-interaction
          vendor/bin/blt blt:telemetry:disable --no-interaction
          vendor/bin/blt circleci:drupal:setup --no-interaction
          vendor/bin/blt tests:phpunit:coverage --no-interaction
    - *save_caches
    - store_test_results:
        path: artifacts/phpunit
    - store_artifacts:
        path: artifacts/phpunit

# Declare all of the jobs we should run.
jobs:
  run-sdssgryphon-codeception-acceptance:
    <<: *sdssgryphon_codeception_acceptance
  run-phpunit-coverage:
    <<: *phpunit_coverage

# Declare a workflow that runs all of our jobs in parallel.
workflows:
  version: 2
  tests:
    jobs:
      - run-sdssgryphon-codeception-acceptance
      - run-phpunit-coverage
