# .github/workflows/deploy_branch.yml
# Deploys current branch to ACE application. Does not work with tags or commits,
# such as a pull_request event.
name: Deploy current branch

# Allow this workflow to be called from other workflows.
on: [workflow_call]

jobs:
  deploy:
    name: Deploy Artifact
    runs-on: ubuntu-latest
    env:
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_HOST: mysql
    container:
      image: pookmish/drupal8ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            vendor
            docroot/core
            docroot/libraries
            docroot/modules/contrib
          key: 4.x-20230622-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            4.x-20230622-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
            4.x-20230622-${{ hashFiles('composer.json') }}-
            4.x-20230622-
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACQUIA_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - run: git config --system --add safe.directory '*'
      - name: Deploy Artifact
        run: |
          git config --global user.email "sws-developers@lists.stanford.edu"
          git config --global user.name "Github Actions"
          ssh-keyscan -t rsa svn-23450.prod.hosting.acquia.com >> /root/.ssh/known_hosts
          composer install -n
          blt blt:telemetry:disable --no-interaction
          blt deploy -v -n
